.fixtures.yml
README.md
manifests/tmpfile.pp
manifests/unit_file.pp
spec/defines/tmpfile_spec.rb
spec/defines/unit_file_spec.rb

This change allows creating unit files and reloading systemd with just a single resource.
It's fully compatible with the manual behavior.

Shortcut for creating unit files / tmpfiles

---

lib/facter/systemd.rb

This reduces a pipe, by only using `awk` for both of operations that of `grep`, and that of `awk`.

only use awk, instead of grep and awk

---

manifests/unit_file.pp
spec/defines/unit_file_spec.rb

This is useful in case the Unit file is a symlink to another one

Add target param for the unit file

---

lib/facter/systemd.rb
spec/unit/facter/systemd_spec.rb
spec/unit/facter/systemd_version_spec.rb

* Use `Facter::Util::Resolution.exec`, which is backwards compatible with older Facter, calls the same method in modern facter
* Adds basic unit testing for facts

Refactor systemd facts

---

README.md
manifests/init.pp
manifests/service_limits.pp
templates/limits.erb

Hi,
Are you planning to improve the module further or is the idea to keep it simple and use it as a "global sync points for reloading systemd"?
Here is a PR for managing resource limits for services started by systemd.  
The module creates _servicename.service_.d/limits.conf file for storing the extra configuration for the service, refreshes systemd and restarts the service.  
Limits are configurable also by using hiera.

Manage resource limits of services

---

templates/limits.erb

MemoryLimit is required to restrict memory on a
systemd service effectvely. Its a more powerful
and working replacement to LimitRSS= which is
not implemented in linux. See man page[1] for
more details.
[1] http://www.dsm.fordham.edu/cgi-bin/man-cgi.pl?topic=systemd.exec&ampsect=5

Add MemoryLimit to limits template

---

manifests/service_limits.pp

The systemd service.d directory for service files apparently needs the seltype of `systemd_unit_file_t`
See also https://github.com/arioch/puppet-redis/pull/202
https://tickets.puppetlabs.com/browse/PUP-7559

Add seltype to systemd directory

---

.fixtures.yml
.rspec
README.md
manifests/init.pp
manifests/networkd.pp
manifests/resolved.pp
manifests/service_limits.pp
manifests/systemctl/daemon_reload.pp
manifests/tmpfile.pp
manifests/tmpfiles.pp
manifests/unit_file.pp
metadata.json
spec/classes/init_spec.rb
spec/classes/systemctl/daemon_reload_spec.rb
spec/classes/tmpfiles_spec.rb
spec/defines/service_limits_spec.rb
spec/defines/tmpfile_spec.rb
spec/defines/unit_file_spec.rb
spec/spec_helper.rb
templates/limits.erb
types/servicelimits.pp
types/unit.pp

* Optimized the limits files
* Added a custom data type for service limits
* Created a class for restarting the daemon so that other modules can
use it cleanly
* Updated tests
Closes #17

Update to support Puppet 4

---

README.md
manifests/dropin_file.pp
spec/defines/dropin_file_spec.rb
types/dropin.pp

Hi,
This solves #15. I know, there is another pull request, which manage drop-in files. But my solution is able to mange multiple drop-in files, even when the service file isn't managed by the `::systemd` module. I've also updated the spec tests and the README.
Regards

Add support for drop-in files

---

README.md

In Puppet 4, had to quote the hash keys in `limits` to make it work.  Otherwise it errors out:
```
Puppet::PreformattedError:
Evaluation Error: Resource type not found: LimitNOFILE at /home/stbenjam/git/puppet-qpid/spec/fixtures/modules/qpid/manifests/router/service.pp:17:9 on node zpm.bitbin.de
```

Quote hash keys in example of service limits

---

README.md

(doc) Adds examples of running the service created

---

manifests/dropin_file.pp
spec/defines/dropin_file_spec.rb

If you wan't to use the same systemd drop-in file for different systemd units, you have to come up with some artificial title for the ::systemd::dropin_file resource. This is because the $name is used as filename. Hence you get a duplicate definition if you want to use the same drop_in file for different units.
Now there is a filename parameter were you can set the filename explicit different from the resource title.

Use the same systemd drop-in file for different units

---

lib/facter/systemd.rb

Return status for systemd services in fact "systemd_internal_services" as string

Fix issue #47

---

README.md
manifests/init.pp
manifests/timesyncd.pp
spec/classes/init_spec.rb

According to timesyncd.conf(5) in man, NTP and FallbackNTP need a space-separated list: https://www.freedesktop.org/software/systemd/man/timesyncd.conf.html

Use a space-separated in timesyncd.conf

---

manifests/tmpfiles.pp

If I understand correctly, this line does what `stdlib`'s `prefix` does so I replaced it.

Replace iterator with stdlib function

---

manifests/service_limits.pp
spec/defines/service_limits_spec.rb

This reduces duplication and fixes a potential duplicate resource of the unit drop in directory.

Reuse the systemd::dropin_file in service_limits

---

Gemfile
manifests/dropin_file.pp
manifests/init.pp
manifests/network.pp
manifests/service_limits.pp
manifests/tmpfile.pp
manifests/unit_file.pp

this check isn't needed anymore for puppet4 and newer

purge legacy puppet-lint checks

---

README.md
data/common.yaml
hiera.yaml
manifests/init.pp
metadata.json

This got pulled out of https://github.com/camptocamp/puppet-systemd/pull/65. The lowest recommended puppet version for this is 4.10.10. In the Vox Pupuli namespace we had a lot of argumentation if this requires a major version bump or not. From a point of defensive programming this should be a major bump.

move params to data-in-modules

---

.travis.yml
Gemfile
Rakefile

This is the code used to generate the changelog from #44. I am not sure if you want to have this in the module, or if you've a modulesync which would drop it. The used commit was tested on Vox Pupuli. Sadly there wasn't a working release in a longer time for the gem (but they are working on it)

implement github changelog generator

---

README.md
manifests/unit_file.pp
spec/defines/unit_file_spec.rb

Allows the deployed units to be enabled and/or started by the module. By default it will leave the units unmanaged.
This is an attempt to supersede PR #55 for which the original submitter appears to have lost interest.

Add enable and active parameters to unit_file

---

Gemfile

It isn't necessary to pin it, facterdb now has all needed facts for 2.5

bump facter to latest 2.x version

---

data/Ubuntu-18.04.yaml
metadata.json

We should wait with this until Ubuntu 18.04 is released as a stable version and facterdb has suitable facts.

add ubuntu 18.04 support

---

manifests/service_limits.pp
spec/defines/service_limits_spec.rb

When ensuring it to be absent, the limits can be undefined since they
don't matter.

Handle ensuring service_limits to be absent

---

README.md
data/common.yaml
manifests/init.pp
manifests/resolved.pp

When using systemd-resolver you can choose to link /etc/resolv.conf to
a "standard" resolv.conf or to a "stub-resolv.conf" that uses 127.0.0.53
resolver provided by it.

Add parameter to select resolver

---

README.md
data/common.yaml
manifests/init.pp
manifests/resolved.pp
spec/classes/init_spec.rb

systemd-resolved supports DNSOverTLS since version 239.
Current Options for this feature are:
*  'opportunistic'
*  'no'
There will be a 'strict' or 'yes' feature in the future.
Signed-off-by: Christian Rebischke <chris@nullday.de>

Add support for DNSoverTLS

---

README.md
data/common.yaml
manifests/init.pp
manifests/journald.pp
metadata.json
spec/classes/init_spec.rb

Make it possible to manage journald settings

Add Journald support

---

manifests/dropin_file.pp
manifests/network.pp
manifests/unit_file.pp
spec/defines/network_spec.rb

Some systemd files could contain sensitive information like .netdev
files associated with wireguard devices that contain private keys
and potentially pre-shared keys.

Allow specifying owner/group/mode/show_diff

---

metadata.json

[`puppetlabs/inifile`](https://forge.puppet.com/puppetlabs/inifile) 3.0.0 was [recently](https://forge.puppet.com/puppetlabs/inifile/changelog) released.  It was a major version bump as they dropped support for puppet 4.

Allow `puppetlabs/inifile` 3.x

---

Rakefile

This project doesn't use a leading `v` on its git tags.

Remove stray `v` from Changelog `config.future_release`

---

manifests/dropin_file.pp
spec/defines/dropin_file_spec.rb

allow Sensitive type for content param

---

data/VirtuozzoLinux-7.yaml
metadata.json

`facter` 3.14 adds support for `os.name` *VirtuozzoLinux* (https://puppet.com/docs/puppet/latest/release_notes_facter.html). This means `os.name` won't resolve to *RedHat* anymore.

add support for 'VirtuozzoLinux 7'

---

manifests/unit_file.pp
spec/defines/unit_file_spec.rb

This ensures the service is stopped before the unit file is removed. Also does some other cleanups on the unit file.

Correct order when ensuring unit files are absent

---

README.md
data/common.yaml
manifests/init.pp
manifests/logind.pp
spec/classes/init_spec.rb
types/logindsettings.pp
types/logindsettings/ensure.pp

Make it possible to manage logind settings. Example configuration:
```
systemd::manage_logind: true
systemd::logind_settings:
HandleSuspendKey: 'ignore'
KillUserProcesses: 'no'
RemoveIPC: 'no'
UserTasksMax: 50000
```
This will allow me (and others) to migrate from https://github.com/NTTCom-MS/eyp-systemd to this module :)
This is (to some degree) a continuation of the discussion in https://github.com/voxpupuli/puppet-confluence/pull/173#issuecomment-468970053. Ping @bastelfreak.

Manage logind service and configuration

---

types/servicelimits.pp

As per [systemd.exec](https://www.freedesktop.org/software/systemd/man/systemd.exec.html), ```OOMScoreAdjust``` takes an integer between -1000 and 1000.

Add OOMScoreAdjust to Systemd::ServiceLimits type

---

manifests/tmpfile.pp
spec/defines/tmpfile_spec.rb

From tmpfiles.d(5)
```
SYNOPSIS
/etc/tmpfiles.d/*.conf
/run/tmpfiles.d/*.conf
/usr/lib/tmpfiles.d/*.conf
```
Just like unit drop in files drop files for the tmpfiles.d must
end in .conf to be noticed.

Force tmpfiles.d drop file to end in .conf

---

manifests/dropin_file.pp
manifests/tmpfile.pp
manifests/unit_file.pp
spec/defines/dropin_file_spec.rb
spec/defines/tmpfile_spec.rb
spec/defines/unit_file_spec.rb
types/dropin.pp
types/unit.pp

The assertion that unit names and drop files names do not
contain a `/` is now done with in the Systemd::Dropin
and `Systemd::Unit` types.
Peviously the assertion was done either within code or just via docs.

Update types to avoid / in unit or drop file name

---

README.md
lib/puppet/provider/loginctl_user/ruby.rb
lib/puppet/type/loginctl_user.rb
spec/spec_helper.rb
spec/spec_helper_local.rb
spec/unit/puppet/provider/loginctl_user/ruby_spec.rb
spec/unit/puppet/type/loginctl_user_spec.rb

Example usage:
```puppet
loginctl_user { 'foo':
linger => enabled,
}
```

Add loginctl_user type/provider

---

data/SLES-12.yaml
data/SLES-15.yaml
metadata.json
spec/acceptance/nodesets/opensuse-15.1.yml
spec/acceptance/nodesets/opensuse-15.2.yml
spec/acceptance/nodesets/opensuse-15.yml
spec/classes/init_spec.rb

I used OpenSUSE docker images in the acceptance test areas as that is what is available on the Docker Hub. They should be a good approximation, however.

Add SLES 12/15 support

---

README.md
manifests/timer.pp
spec/defines/timer_spec.rb

The defined type allows easy creation of the timer and service
unit at the same time.
Examples of usage
```puppet
systemd::timer{'runoften.timer':
timer_source   => "puppet:///modules/${module_name}/runoften.timer",
service_source => "puppet:///modules/${module_name}/runoften.service",
}
```
or a trivial daily run as:
```puppet
systemd::timer{'daily.timer':
timer_content  => "[Timer]\nOnCalendar=daily\nRandomizedDelaySec=1d\n",
service_content => "[Service]\nType=oneshot\nExecStart=/usr/bin/touch /tmp/file",
}
```
If neither `service_content` or `service_source` are specified then no
service unit will be created.
The service unit name can also be specified.
```puppet
systemd::timer{'daily.timer':
timer_content  => "[Timer]\nOnCalendar=daily\nRandomizedDelaySec=1d\nUnit=touch-me-today.servi …
```

New systemd::timer define type

---

manifests/dropin_file.pp
manifests/service_limits.pp
spec/defines/dropin_file_spec.rb

This commits add support for passing the service_ignore_defaults parameter to the file resources being handled in the dropin_file definition. It then adds the parameter to service_limits which use dropin_file so that consumers of this resource can pass it.
This is needed in order to support RHEL based operating systems again in puppet-rabbitmq module where the Puppet run is idempotent after moving to the systemd module [1].
[1] https://github.com/voxpupuli/puppet-rabbitmq/issues/836

Add selinux_ignore_defaults support to dropin_file and service_limits

---

README.md
manifests/init.pp
spec/classes/init_spec.rb

Add a factory for dropin files so they can be simply defined in hiera

add factory for dropin files

---

manifests/init.pp

90cc85cbccc00cc51b775639eb9c20293446e63e introduced this but with a typo in the
name so puppet-strings couldn't find it.

Fix typo in parameter name in class documentation

---

manifests/logind.pp
spec/classes/init_spec.rb

For the loginctl user parameter lists, it is easier to set them as an array (that way I can append or de-dupe easily).
Psudo hiera:
```yaml
systemd::logind_settings:
KillExcludeUsers: 
- root
```
```yaml
systemd::logind_settings:
KillExcludeUsers: 
- other_user
```

Permit using arrays to make extending lists easier

---

README.md
manifests/init.pp
manifests/logind.pp
spec/classes/init_spec.rb

This should make it much easier to build `loginctl_users` for folks running with an ENC.

Add parameter for ENCs to make loginctl_users easily

---

REFERENCE.md
types/journaldsettings.pp
types/logindsettings.pp

For https://github.com/camptocamp/puppet-systemd/pull/171 I was regenerating REFERENCE.md and noticed that it was out of date. It also contained ugly control statements. This fixes it.

Move lint control statements out of documentation

---

.sync.yml
spec/spec_helper.rb
spec/spec_helper_local.rb
spec/unit/facter/systemd_spec.rb
spec/unit/facter/systemd_version_spec.rb

This is recommended by puppetlabs_spec_helper and avoids a deprecation warning.

Convert from mocha to rspec-mocks

---

manifests/init.pp
spec/classes/init_spec.rb

Update the cache parameter on init class to match the allowed values for
resolved.
This addresses the issue brought up here: https://github.com/camptocamp/puppet-systemd/issues/166 
https://github.com/camptocamp/puppet-systemd/pull/140 initally added the ability to use the no-negative option for resolved, however it did not include the corresponding adjustment to allow controlling the value from the init class.

Allow additional option for $cache parameter

---

README.md
data/common.yaml
manifests/init.pp
manifests/udev/rule.pp
manifests/udevd.pp
spec/classes/init_spec.rb
spec/defines/udev_rules.spec
templates/udev_conf.epp
templates/udev_rule.epp

With `udev` part of systemd these days, it is handy to have a place to set custom udev rules (for folks that need that like me).

Add management of udev objects

---

manifests/init.pp
manifests/resolved.pp

d1c2ec39f2a238033a64345f31829dc6b1c0b6b9 added use_stub_resolver as a parameter but there's a mismatch between the code and documentation.  While in practice /var/run is a symlink to /run and the mismatch doesn't really matter, it's better to have them match to avoid confusion.

Correct path in use_stub_resolver documentation

---

metadata.json

97dd16fa32886b5b0f77a6f38a4953d4c1511c0e was a breaking change. Bumping the version helps consuming modules to make a distinction with the following code:
```puppet
$metadata = load_module_metadata('systemd')
if SemVer($metadata['version']) >= SemVer('3.0.0') {}
```
My use cases is:
```puppet
systemd::unit_file { 'myservice.socket':
content => file('mymodule/myservice.socket'),
enable  => true,
active  => true,
}
systemd::unit_file { 'myservice.service':
content => file('mymodule/myservice.service'),
enable  => true,
active  => true,
}
$metadata = load_module_metadata('systemd')
if SemVer($metadata['version']) >= SemVer('3.0.0') {
Systemd::Unit_file['myservice.socket'] -> Systemd::Unit_file['myservice.service']
}
```
This allows me to maintain Puppet 5 support for a bit longer while also …

Bump version to 3.0.0-rc0

---

metadata.json

Allow use with the latest versions of these puppetlabs modules.

metadata: allow stdlib 7.0.0 and inifile 5.0.0

---

REFERENCE.md
manifests/dropin_file.pp
manifests/journald.pp
manifests/logind.pp
manifests/network.pp
manifests/resolved.pp
manifests/service_limits.pp
manifests/timesyncd.pp
manifests/tmpfile.pp
manifests/udev/rule.pp
manifests/udevd.pp

In various places `@attr` was used instead of `@param`. It also didn't use the `@summary` tag which led to odd summaries. Then some indenting was incorrect.
It also uses a newer version of puppet-strings which generates a list of parameters with links.

Correct puppet-strings documentation

---

REFERENCE.md
manifests/dropin_file.pp
spec/defines/dropin_file_spec.rb

It is very common that a drop in file should notify a service that's managed elsewhere. This adds a parameter to do so which then uses a collector.
Review notes:
* Should the parent directory also notify the service? My main reasoning be that if it purges unknown files, it should also notify the service. I don't even know if that works
* I made it default to false to be compatible. This makes it a bit hard to use though.
* Should this be exposed on any defined type that uses dropin_file?

Add notify_service support to dropin_file

---

manifests/unit_file.pp
spec/defines/unit_file_spec.rb

- just as for systemd::dropin_file, accept Datatype Sensitive for $content

Accept Datatype Sensitive for $content

---

manifests/unit_file.pp

Required if you want to use this type with eg. [`node_encrypt::secret`](https://github.com/binford2k/binford2k-node_encrypt).

Allow `systemd::unit_file` `Deferred` `content`

---

REFERENCE.md
data/common.yaml
manifests/init.pp
manifests/networkd.pp
spec/classes/init_spec.rb

Add option to purge non-managed networkd files

---

data/CentOS-8.yaml
data/RedHat-8.yaml

DefaultIOAccounting and DefaultIPAccounting are supported by CentOS 8
sowe can enable them as well.

CentOS 8: Enable more accounting options

---

README.md
REFERENCE.md
functions/escape.pp
spec/functions/escape_spec.rb

Add a systemd escape function.
```puppet
systemd::escape('/foo/bar')
```
returns `-foo-bar`
while the path escape can be executed as
```puppet
systemd::escape('/foo/bar',true)
```
to return 'foo-bar'

Add systemd::escape function

---

data/Debian-11.yaml
metadata.json

I got the data from the debian/bullseye64 Vagrant box:
```
```

Add Debian 11 support

---

data/CentOS-7.yaml
data/CentOS-8.yaml
data/OracleLinux-7.yaml
data/OracleLinux-8.yaml
hiera.yaml

Use the `os.family` fact for RedHat based systems since they will all have same defaults.  This ensures CentOS 8 replacements like Alma Linux and Rocky Linux will work without having to add additional duplicate Hiera files.  I ran into this issue with modules where I had Scientific Linux tests enabled, which is another RedHat clone.

Use os.family for RedHat based Hiera data

---

data/RedHat-9.yaml
metadata.json

Add CentOS/RHEL 9 support. Without this change puppet-systemd will
likely fail with the following error:
Evaluation Error: Error while evaluating a Function Call, Class[Systemd]:
expects a value for parameter 'accounting'
(file: /etc/puppet/modules/systemd/manifests/service_limits.pp, line: 40, column: 3)
Tested on Centos 9 Stream.
Signed-off-by: Michele Baldessari <michele@acksyn.org>

Add CentOS/RHEL 9 support

---

CHANGELOG.md
metadata.json

Release 3.5.0

---

manifests/init.pp

In ff098e030b95fa95131bb8e65585c8bdecc23a3d the defaults were moved from data/common.yaml to init.pp but this was missed. That means on unsupported platforms it no longer works to include the class (which should be a noop).

Declare a default for $accounting

---

README.md

The example in README was had used `dns_stub_resolver` when the
parameter is actually `use_stub_resolver`

Correct use_stub_resolver example in README

---

manifests/timesyncd.pp

systemd has switched in version 215 from Servers= to NTP=
Debian 8 has older systemd version and needs the NTP= setting

timesyncd compatibility with Debian 8

---

README.md
REFERENCE.md
manifests/modules_load.pp
manifests/modules_loads.pp
spec/defines/modules_load_spec.rb

A new type `systemd::modules_load` can add entries
to the directory `/etc/modules-load.d`.
```puppet
systemd::modules_load{'ipmi.conf':
content => "ipmi\n",
}
```
Upon modification `systemctl  start systemd-modules-load.service` will
be called to activate the new file.

Manage entries in modules-load.d directory

---

functions/escape.pp
spec/functions/escape_spec.rb

We also need to escape dashes in unit names, for instance for .swap services on device nodes with dashes in them.
systemd-escape escapes dashes:
```
dev-disk-by\x2did-scsi\x2d0QEMU_QEMU_HARDDISK_drive\x2dua\x2dswap
```
but this function does not (yet).
In the long term, we may want to more closely match the behaviour of
systemd's unit-name.c, but this is all I need for now.
Fix systemd::escape a bit

systemd::escape: Also escape - (dash)

---

README.md
REFERENCE.md
data/RedHat-8.yaml
data/RedHat-9.yaml
manifests/init.pp
manifests/install.pp
spec/classes/init_spec.rb

On CentOS 8 and 9 systemd-resolved must be installed to use
systemd-resolved.
Install the package if `manage_resolved` is `true` which is not the default.
Since the `systemd_internal_services` fact will only be populated
once the package is installed a second puppet run will be required
to actually configure systemd-resolved.

Install systemd-resolved on CentOS 8 and 9

---

REFERENCE.md
manifests/unit_file.pp
spec/defines/unit_file_spec.rb

The parameter comes from the file resource type:
* https://puppet.com/docs/puppet/7/types/file.html#file-attribute-selinux_ignore_defaults.
With the new parameter in this defined resource we can configure the same param for the underlying file resource for the systemd unit.
Upstream docs:
* https://github.com/puppetlabs/puppet/blob/053ee58b62abd2063d6b05a077a7b6991769b9bd/lib/puppet/type/file/selcontext.rb#L85-L94
* https://github.com/puppetlabs/puppet/commit/ac2262d071cc2c9841843354585980696c689ca3

unit_file: Implement selinux_ignore_defaults

---

README.md
REFERENCE.md
manifests/coredump.pp
manifests/init.pp
spec/classes/init_spec.rb
spec/type_aliases/systemd_coredumpsettings_spec.rb
types/coredumpsettings.pp

Manage the systemd-coredump configuration.
* `systemd::manage_coredump` to enable everything
* `systemd::coredump_settings` will manage `/etc/systemd/coredump.conf`
* `systemd::backtrace` if true will add `--backtrace` to the `systemd-coredump` call.
So typical use would be
```puppet
class{'systemd':
manage_coredump   => true,
coredump_settings => {
'Storage' => 'external',
},
coredump_backtrace => true,
}
```
to enable storing cores on disk and writing backtraces to
the journal.

Manage systemd-coredump config and setup

---

manifests/timer.pp
spec/defines/timer_spec.rb

Without this, issues like:
```
cvmfs-fsck.timer: Refusing to start, unit cvmfs-fsck.service to trigger not loaded.
```
may be observed.

timer: timer unit must depend on service unit.

---

data/RedHat-8.yaml
spec/classes/init_spec.rb

MR #246 started installing the `systemd-resolved` package
on RedHat 8 and 9 however this quite wrong for 8 where
systemd-resolved is not a sub package.
```
> rpm -qf /usr/bin/systemd-resolve
systemd-239-56.el8.x86_64
```

Do not install  systemd-resolved RedHat 8

---

REFERENCE.md
manifests/init.pp
manifests/resolved.pp
spec/classes/init_spec.rb

If the parameter is true (default) then `/etc/resolv.conf` will
be managed when `manage_resolved` is true.

New parmater manage_resolv_conf for /etc/resolv.conf

---

.github/workflows/ci.yml
.sync.yml
spec/acceptance/default_spec.rb
spec/acceptance/resolved_spec.rb
spec/acceptance/systemd_spec.rb
spec/spec_helper_acceptance.rb

Addition of trivial acceptance tests

Addition of Trivial Acceptance Tests

---

README.md
REFERENCE.md
manifests/init.pp
manifests/resolved.pp
spec/acceptance/resolved_spec.rb
spec/classes/init_spec.rb

If `systemd-resolved` is stopped but managed via
```
class{'systemd:
managed_resolved => true,
resolved_ensure  => 'stopped',
}
```
Then the files in `/var/run/systemd/resolv` will either
be stale(just stopped) or missing(after reboot). In both cases it
makes no sense to manage `/etc/resolv.conf`.
More over for the case where `systemd-resolved` has just
been stopped reinstate `/etc/resolv.conf` as `/run/systemd/resolve/resolv.conf`.
Fixes #203

Don't manage /etc/resolv.conf if systemd-resolved is stopped

---

README.md
data/RedHat-7.yaml
spec/acceptance/resolved_spec.rb
spec/classes/init_spec.rb

Following #246 and #254 systemd-resolved was installed on family
RedHat 9 only.
On RedHat 7 a systemd-resolved package is now installed.
For information it is only RedHat 8 that does not have a systemd
resolved package.

Install systemd-resolved on RedHat 7

---

REFERENCE.md
manifests/unit_file.pp
spec/defines/unit_file_spec.rb

This allows people to pass all options the service resource type accepts
to `systemd::dropin_file`. This is required to enable people to make a
migration from legacy code with systemd reload + file/service resource
to this module.

dropin_file: Implement service_parameters hash

---

manifests/udev/rule.pp
spec/defines/udev_rules_spec.rb

systemd::udev::rule: param rules now defaults to `[]` / fix broken tests

---

REFERENCE.md
manifests/unit_file.pp
spec/defines/unit_file_spec.rb

We now have a `$service_parameters` hash that's passed to the service
resource. It should be used to set hasrestart/hasstatus.

unit_file: deprecate hasrestart/hasstatus params

---

metadata.json

This is follow-up of 1698451e2069f4c067ba394a05703aa559c03863 and adds
CentOS 9 to supported operating systems. The required logic was
implemented by that change but the supported versions of CentOS were
not updated by that commit.
n/a

Add CentOS 9 to supported operating systems

---

README.md
lib/puppet/functions/systemd/systemd_escape.rb
spec/functions/systemd_escape_spec.rb

This PR is a proposal for #242 and its intended to replace the current function `systemd::escape`.
This PR add a function `systemd::systemd_escape` based on the system call systemd-escape.
See #220 and #95
`rubocop:disable Style/OptionalBooleanParameter` is required here, otherwise puppet [wont detect](https://github.com/voxpupuli/puppet-systemd/runs/4913907935?check_suite_focus=true) the optional parameter.
Fixes #242

Add function systemd::systemd_escape

---

README.md
manifests/init.pp
spec/classes/init_spec.rb

I was a bit surprised to discover that the default target for systemd was not already something this class managed.
Merging this should probably result in a meaningful version bump since folks who want a different target will need to set one explicitly.  The default from systemd upstream is multi-user.target thus that is what I selected.

Add parameter to manage default target

---

README.md
manifests/init.pp
manifests/oomd.pp
spec/classes/init_spec.rb
spec/type_aliases/systemd_oomdsettings_spec.rb
types/oomdsettings.pp

Add parameters to manage systemd-oomd and its configuration.

Add management of systemd-oomd

---

manifests/resolved.pp

This is a trivial/tiny optimization.

systemd::resolved: save readlink's value to avoid calling it twice

---

templates/udev_conf.epp

These days systemd-udev includes a note about udev in the initrd.  Adding that comment to the template for folks so they have a hint about why their udev.conf changes may not be taking effect.
N/A

Add comment hint about initrd for folks

---

REFERENCE.md
spec/type_aliases/unit_spec.rb
types/unit.pp

Previously lots of unit names like
```
this is a service with spaces in.service
```
were permitted for instance.
From systemd.unit
> Valid unit names consist of a "name prefix" and a dot and a suffix specifying the unit type. The "unit prefix" must consist of one or more valid characters (ASCII letters, digits, ":", "-", "_", ".", and "\"). The total length of the unit name including the suffix must not exceed 256 characters. The type suffix must be one of ".service", ".socket", ".device", ".mount", ".automount", ".swap", ".target", ".path", ".timer", ".slice", or ".scope".
in addition we allow `@` to cover the case of template or template instance.

Make Systemd::Unit type stricter

---

README.md
REFERENCE.md
manifests/manage_dropin.pp
manifests/manage_unit.pp
spec/defines/manage_dropin_spec.rb
spec/defines/manage_unit_spec.rb
spec/type_aliases/systemd_unit_install_spec.rb
spec/type_aliases/systemd_unit_service_exec_spec.rb
spec/type_aliases/systemd_unit_service_spec.rb
spec/type_aliases/systemd_unit_unit_spec.rb
templates/unit_file.epp
types/unit/install.pp
types/unit/service.pp
types/unit/service/exec.pp
types/unit/unit.pp

A new type is added to create a service unit file from a template and then manage the resulting service.
Example
```puppet
systemd::manage_unit { 'myrunner.service':
$unit_entry           => {
'Description' => ['My great service', 'has two lines of description'],
},
$service_entry        => {
'Type'        => 'oneshot',
'ExecStart'   => '/usr/bin/doit.sh',
},
$install_entry        => {
'WantedBy'      => 'multi-user.target',
},
}
```
will generate and manage a new systemd unit from a template.
Similarly to create drop in files from the same template:
```puppet
systemd::manage_dropin {'myconf.conf':
ensure        => present,
unit          => 'myservice.service',
service_entry => {
'Type'      => 'oneshot',
'ExecStart' => ['', '/usr/bin/doit.sh'],
}
}
```
Not every systemd directive has …

New systemd::manage_unit, systemd::manage_dropin types

---

data/Debian-11.yaml
data/Ubuntu-20.04.yaml
manifests/init.pp
manifests/install.pp
spec/classes/init_spec.rb

feat: manage timesyncd package on Debian >= 11 and Ubuntu >= 20.04

---

REFERENCE.md
spec/defines/service_limits_spec.rb
spec/type_aliases/systemd_servicelimits_spec.rb
types/servicelimits.pp

Support specification of the  absolute limit on swap usage of the executed processes in this unit.
For example
```puppet
systemd::service_limits{'condor.service':
limits => {
'MemorySwapMax' => '0',
}
}
```
* https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#MemorySwapMax=bytes

Allow MemorySwapMax to be specified as service limit

---

data/Debian-8.yaml
manifests/timesyncd.pp
metadata.json

Debian 8 was end of life 2020-06-30
https://wiki.debian.org/DebianReleases
more over acceptance jobs now fail with:
```json
{"stream":"\u001b[91mW: GPG error: http://deb.debian.org/ jessie-updates InRelease: The following signatures were invalid: KEYEXPIRED 1668891673\nW: GPG error: http://deb.debian.org/ jessie Release: The following signatures were invalid: KEYEXPIRED 1668891673\n\u001b[0m"}
```

Remove debian 8 support

---

REFERENCE.md
manifests/service_limits.pp
spec/defines/service_limits_spec.rb

Since 97dd16fa32886b5b0f77a6f38a4953d4c1511c0e this parameter is a bad idea. It doesn't do a daemon reload and it may restart at the wrong time. In fact, I'd argue it's always been a bad idea.
The recommended alternative to this is to manage the service explicitly and let Puppet handle it. There is an automatic notify that takes care of it.
Fixes #190

Remove restart_service on service_limits define

---

REFERENCE.md
manifests/dropin_file.pp
manifests/service_limits.pp
spec/defines/service_limits_spec.rb

This builds on 81f3eb5e7612e50726fa8450ca161bbe271419a1 which allowed services to be notified automatically. This changes it to default behavior.
Fixes #74
It's currently a draft since it includes https://github.com/camptocamp/puppet-systemd/pull/193 which I think it may depend on.

Notify services by default on drop in files

---

REFERENCE.md
manifests/service_limits.pp

In 8a9e03a4d6a58a5a5083d7ead60dcbc87f727d2f the parameter was removed, but this makes it very hard for modules to be compatible with both < 4 and >= 4. Requiring >= 4 will be painful, so this adds the parameter again but only accepts the parameter false.
A concrete example is the puppet-redis module which sets restart_service to false to prevent a restart. This would be compatible with both the old and new behavior, making upgrades smoother.

Add restart_service parameter on service_limits for compatibility

---

manifests/timer.pp

I was reading the code and vim wouldn't highlight that line properly...

systemd::timer: fix before's argument to use the proper syntax

---

REFERENCE.md
manifests/manage_dropin.pp
manifests/manage_unit.pp
spec/defines/manage_dropin_spec.rb
spec/defines/manage_unit_spec.rb
templates/unit_file.epp
types/unit/timer.pp

This makes it easier to deal with timer units. Right now it only implements OnCalendar, but it should be easy to expand to all types.

Add timer_entry to manage_{dropin,unit}

---

README.md

A $ sign is not valid syntax in the hash definition. Removing it gives a valid manifest file.
Fixes #325

Fix `manage_unit` example in README.md

---

README.md
REFERENCE.md
manifests/manage_unit.pp
manifests/modules_load.pp

The documentation and example mix various styles.  For consistency, follow the [style guide from Puppet](https://www.puppet.com/docs/puppet/7/style_guide.html).
Some examples in the README could be moved to the classes documentation to end in REFERENCE.md, but it is another story.

Stick to the Puppet language style guide

---

spec/defines/manage_unit_spec.rb

The catalog is compiled for every example, so testing the same resource in a single example is faster.

Group spec expectations in a single example

---

REFERENCE.md
spec/defines/manage_unit_spec.rb
spec/type_aliases/systemd_unit_timer_spec.rb
types/unit/timer.pp

The timer directives for unit files is now complete for options present in the man page of systemd-253.
For example:
```puppet
systemd::manage_unit{'my.timer':
ensure => present,
unit_entry => {
'Description' => 'my timer',
},
timer_entry => {
'Calendar' => 'daily',
'AccuracySecs' => '1 hour',
},
}
```
Previously only the 'Calendar' directive was available and this patch also includes a bug fix for that.
Previously
```
systemd::manage_dropin{'my.timer':
ensure => present,
unit => 'myunit.service',
timer_entry => {
'Calendar' => ['','daily'],
},
}
```
with an empty resetting first `''` element was not permitted and now it is..

Addition of timer directives to manage_unit and manage_dropin

---

REFERENCE.md
spec/defines/manage_dropin_spec.rb
spec/defines/manage_unit_spec.rb
spec/type_aliases/systemd_unit_unit_spec.rb
types/unit/unit.pp

Allow `DefaultDependencies` to be specified as a `Boolean` in the `[Unit]` section of a templated unit or dropin file.
e.g.
```puppet
systemd::manage_unit{'my.service':
ensure     => present,
unit_entry => {
'DefaultDependencies' => false,
},
}
```
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#DefaultDependencies=

Allow DefaultDependencies to be set in [Unit] section

---

metadata.json

Puppetlabs-inifile v6.0.0 has been released yet this module locks to < 6.0.0. This can cause cascading issues installing the latest of other modules as a result.
Fixes https://github.com/voxpupuli/puppet-systemd/issues/336

Increase inifile dependency upper version to < 7.0.0

---

REFERENCE.md
manifests/manage_dropin.pp
manifests/manage_unit.pp
spec/defines/manage_dropin_spec.rb
spec/defines/manage_unit_spec.rb
spec/type_aliases/systemd_unit_path_spec.rb
templates/unit_file.epp
types/unit/path.pp

The path directives for unit files is now complete for options present in the man page
of systemd-253.
The parameter `path_entry` can now be specified for `systemd::manage_unit` or
`systemd::manage_dropin`.
For example:
```puppet
systemd::manage_unit{'etc-passwd.path':
ensure     => present,
unit_entry => {
'Description' => 'Monitor /etc/passwd',
},
path_entry => {
'PathChanged' => '/etc/passwd',
'Unit'        => 'etc-passwd-updates.service',
},
}
```
or
```puppet
systemd::manage_dropin{'trigger-limit.conf':
ensure     => present,
unit       => 'etc-passwd.path',
path_entry => {
'TriggerLimitBurst' => 100,
},
}
```
https://www.freedesktop.org/software/systemd/man/systemd.path.html
Additional commits:
* Correct timer_entry error message on a non-timer
* Group spec expectations in a single …

Addition of path directives to manage_unit/dropin

---

REFERENCE.md
manifests/manage_dropin.pp
spec/defines/manage_dropin_spec.rb
spec/type_aliases/systemd_unit_service_spec.rb
types/unit/service.pp

Addition of LimitCOR to `[service]` section of
`systemd::manage_unit` and `systemd::manage_dropin`
Added as penance for giving a wrong guess twice to someone how to do this. Always confuses me since while:
`systemctl show sshd.service -t LimitCORESoft` has a value it cannot be set as I understand it.
There is some duplication here with the existing `systemd::service_limits` but that is fine.
* https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Properties

Allow LimitCORE in [Service] for manage_unit/dropin

---

metadata.json

Relax stdlib dependency version requirements

---

spec/defines/manage_dropin_spec.rb
templates/unit_file.epp

It's useful to see clearly see that files deployed with puppet are deployed with puppet.
Add a comment to top of files deployed by `systemd::manage_unit` and  `systemd::manage_dropin`.
e.g 
```puppet
systemd::manage_unit{'redis@.service':
ensure          => present,
unit_entry    => {
'Description' => 'redis server instance on port %i',
},
service_entry => {
'Type'      => 'simple',
'User'      => 'redis',
'Group'     => 'redis',
'ExecStart' => '/usr/bin/redis-server /etc/redis/redis_%i.conf',
'ExecStop'  => '/usr/bin/redis-cli -p %i shutdown',
'PIDFile'   => '/run/redis/%i.pid',
},
}
```
will now deploy `/etc/systemd/system/@redis@.service` with a first line of:
```
```

Add comment in manage_unit deployed files

---

REFERENCE.md
manifests/manage_unit.pp
spec/defines/manage_unit_spec.rb

Removing a unit file with `systemd::manage_unit` with the following:
```
systemd::manage_unit {'foo.service':
ensure     => 'absent',
}
```
This is not possible and a `service_entry` and `unit_entry` must be specified as the unit name
is in the service namespace.
Remove insistence for `unit_entry` and  `service_name` parameter for the absent case.
For the `ensure => 'present`` the `unit_entry` is no longer required since it is perfectly possible to create
units without any `[Unit]` section. 
Also improve failure message when `service_entry` is not specified for service unit.

No insistence on unit_entry ever or service_entry with absent manage_unit

---

REFERENCE.md
spec/type_aliases/systemd_unit_service_spec.rb
spec/type_aliases/systemd_unit_unit_spec.rb
types/unit/service.pp
types/unit/unit.pp

* Allow  `StandardOutput` and `StandardError` in `[Service]` section.
* Allow  `RequireMountsFor` in `[Unit]` section.
* https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=
* https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardError=
* https://www.freedesktop.org/software/systemd/man/systemd.unit.html#RequiresMountsFor=
Note documentation for RequiresMountsFor is actually incomplete [1]
* [1] https://serverfault.com/questions/1085820/systemd-requiresmountsfor-multiline-syntax
Fixes: #321

Support StandardOutput, StandardError and RequiresMountsFor.

---

REFERENCE.md
spec/type_aliases/systemd_unit_service_spec.rb
types/unit/service.pp

Support use of `WorkingDirectory` directive in `[Service]` section of `systemd::manage_unit` and `systemd::manage_dropin`
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=
Fixes: #299

Allow WorkingDirectory to be specified in [Service]

---

REFERENCE.md
manifests/manage_unit.pp

Fixes: 5371ac0db747 ("Socket support for manage unit and dropin")

Correct syntax in manage_unit socket example

---

REFERENCE.md
manifests/manage_dropin.pp
spec/type_aliases/systemd_unit_service_spec.rb
types/unit/service.pp

```puppet
systemd::manage_dropin { 'maxloglevel.conf':
ensure        => present,
unit          => 'chatty.service',
service_entry => {
'LogLevelMax' => 'warning',
}
}
```
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#LogLevelMax=

Allow LogLevelMax to be set in [Service]

---

REFERENCE.md
spec/type_aliases/systemd_unit_service_spec.rb
types/unit/service.pp

allow to set StandardInput like it is in the example for xinetd style systemd socket: https://github.com/voxpupuli/puppet-systemd/blob/master/manifests/manage_unit.pp#L63
* https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardInput=

allow to set StandardInput on service unit

---

data/Ubuntu-18.04.yaml
metadata.json

https://ubuntu.com/blog/18-04-end-of-standard-support

Drop Ubuntu 18.04 which went out of standard support in May 2023

---

REFERENCE.md
manifests/init.pp
manifests/resolved.pp
spec/classes/init_spec.rb

Untested now, but something I need in my setup and having a PR makes testing easier.

Implement DNSStubListenerExtra for resolved.conf

---

metadata.json

This module doesn't have OracleLinux 7 specific code. We enabled acceptance tests after OracleLinux 7 was added to metadata.json. We learned that the OracleLinux 7 repos are broken and we cannot test it. We are purging it from all modules. Because of that we don't label it as backwards-incompatible.

Drop OracleLinux 7 from metadata.json

---

README.md
spec/acceptance/resolved_spec.rb
spec/classes/init_spec.rb

In particular with Debian 11->12 systemd-resolved is now a sub package
that must be installed.
Clearly there are no tests running for Debian 12 yet.

Support Debian 12

---

README.md
REFERENCE.md
spec/type_aliases/systemd_coredumpsettings_spec.rb
types/coredumpsettings.pp

Incorrect coredump paramters were added.
It should be `KeepFree` and `MaxFree` was never valid.
https://www.freedesktop.org/software/systemd/man/latest/coredump.conf.html#MaxUse=
* Fixes #398

Correct coredump parameter from MaxFree to KeepFree

---

REFERENCE.md
manifests/manage_dropin.pp
spec/defines/manage_dropin_spec.rb
spec/type_aliases/unit_spec.rb
types/unit.pp

This allows relations to be set up between similar instances of two templated units.
For example:
```puppet
systemd::manage_dropin{'user-aklog.conf':
ensure     => present,
unit       => 'user@.service',
unit_entry => {
'Documentation' => 'Run an aklog before we start systemd --user',
'After'         => ['user-aklog@%i.service'],
'Requires'      => ['user-aklog@%i.service'],
},
}
```
Previously the `%` character was considered illegal in a unit name.

Allow percent (%) character in unit names.

---

REFERENCE.md
manifests/init.pp
manifests/resolved.pp
spec/classes/init_spec.rb

Starting with
```puppet
class{ 'systemd':
manage_reolved => true,
cache          => false,
}
```
note that the cache parameter is currently `false` by default and an explicit `Cache=no` would not be set. Instead nothing would be done.
This patch maintains backwards compatibility in that the default still results in no modification to `/etc/systemd/resolved.conf`.
However an explicit setting of `cache => false` with this patch will now add `Cache=no` to `resolved.conf`.

systemd::cache = false result was vague.

---

REFERENCE.md
spec/type_aliases/systemd_unit_unit_spec.rb
types/unit/unit.pp

Allow `StartLimitIntervalSec` and `StartLimitBurst` to be set in the `[unit]` section of a managed drop or unit file.
https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#StartLimitIntervalSec=interval

Support `StartLimitIntervalSec` and  `StartLimitBurst`

---

.gitignore
README.md
REFERENCE.md
tasks/systemctl_show.json
tasks/systemctl_show.rb

```text
bolt task run systemd::systemctl_show unit_name=puppet.service -t controller-0
Started on controller-0...
Finished on controller-0:
{
"MainPID": "686",
"LoadState": "loaded",
"ActiveState": "active",
"SubState": "running",
"UnitFileState": "enabled"
}
```

Add bolt task to return unit state in a more parsable way

---

REFERENCE.md
manifests/init.pp
manifests/udevd.pp
spec/classes/init_spec.rb

Add a parameter that will purge all non managed files from `/etc/udev/rules.d directory`
Defaults to `false`
fixes #291

Add parameter to manage /etc/udev/rules.d directory

---

manifests/unit_file.pp
metadata.json
spec/defines/unit_file_spec.rb

Currently the `systemd::unit_file` type ignores the `ensure` parameter if `target` is defined. This allows the `ensure` parameter to be absent and thus removing the unit file if `target` is set.

`systemd::unit_file`: Ensure link gets removed on `ensure => absent`

---

README.md
REFERENCE.md
manifests/init.pp
spec/classes/init_spec.rb

Units and dropins can now be created from hiera records:
e.g.
```yaml
systemd::manage_dropins:
myconf.conf:
ensure: present
unit: myservice.service
service_entry:
Type: oneshot
ExecStart:
- ''
- '/usr/bin/doit.sh'
systemd::manage_units:
myservice.service:
unit_entry:
Description: My Customisation
service_entry:
CPUWeight: 2000
```
Fixes #435

Create manage_unit, manage_dropin types from hiera

---

REFERENCE.md
manifests/init.pp

The code doesn't actually use `create_resources` anymore. This commit makes the doc string consistent with the other similar parameters.

`init`: `service_limits` param: don't refer to `create_resources`

---

REFERENCE.md
manifests/unit_file.pp

@cocker-cc correctly mentioned in
https://github.com/voxpupuli/puppet-systemd/commit/7f63dfa49850a860b24a93874fe5c5f4430f9edc#commitcomment-139614892 that after #405 `ensure=file` breaks due to `stdlib::ensure` not being able to handle that. As `file` is any way only a synonym for `present`, let's just remove it from the possible values.
https://github.com/voxpupuli/puppet-systemd/commit/7f63dfa49850a860b24a93874fe5c5f4430f9edc#commitcomment-139614892

Don't allow ensure=file anymore for systemd::unit_file

---

REFERENCE.md
data/Debian-family.yaml
data/RedHat-family-7.yaml
manifests/init.pp
manifests/install.pp
spec/acceptance/nspwan_spec.rb
spec/classes/init_spec.rb

New parameters `systemd::manage_nspawn` defaulting to `false`, if `true` it will ensure that the `machinectl` and `systemd-nspawn` commands are available.
When `true` the systemd_internal_services fact will be populated.
```
facter -p systemd_internal_services
{
systemd-nspawn@.service => "disabled",
}
```

New parameters to manage systemd-nspawn

---

REFERENCE.md
manifests/user_service.pp
metadata.json
spec/defines/user_service_spec.rb

New defined type `systemd::user_service` has two roles:
It can globally enable a user unit for all users. e.g:
```puppet
systemd::user_service { 'systemd-tmpfiles-clean.service':
enable => true,
global => true,
}
````
It can start/stop/enable/disable a service running for a particular user. e.g
```puppet
systemd::user_service { 'ssh-agent.socket':
ensure => 'running',
enable => true,
user   => 'steve',
}
```
The type instance can also be notified to reload the unit running under a `systemd --user` instance.
```puppet
file { '/home/steve/.gpg.conf':
ensure  => file,
content => 'custom',
notify  => Systemd::User_service['steve-gpg-agent.socket'],
}
systemd::user_service { 'steve-gpg-agent.socket':
ensure => true,
unit   => 'gpg-agent.socket',
enable => true,
user   => 'steve',
}
```
Note …

Manage units running under `systemd --user` instance

---

REFERENCE.md
manifests/daemon_reload.pp
metadata.json
spec/defines/daemon_reload_spec.rb

This change increased the minimum required Puppet version to 6.24.0 or 7.9.0 [PUP-5704](https://puppet.atlassian.net/browse/PUP-5704) to support arrays to the command attribute of the exec type.
Support the calling the `systemd --user daemon-reload` for a particular user.
Example run:
```puppet
notify{'junk':
notify => Systemd::Daemon_reload['user_foobar'],
}
systemd::daemon_reload{'user_steve':
user => 'steve',
}
```
This results on a Fedora box:
```
Notice: /Stage[main]/Main/Notify[junk]/message: defined 'message' as 'junk'
Notice: /Stage[main]/Main/Systemd::Daemon_reload[user_steve]/Package[systemd-container]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Main/Systemd::Daemon_reload[user_steve]/Exec[systemd-user_steve-systemctl-user-steve-daemon-reload]: Triggered 'refresh' …
```

Support reload of instances of systemd --user

---

data/Debian-10.yaml
metadata.json
spec/classes/init_spec.rb
spec/defines/daemon_reload_spec.rb

Debian 10 is dead upstream, we don't support it anymore.

Drop EoL Debian 10 support

---

manifests/service_limits.pp

Fixes: 988d2c7db2db ("Deprecate `systemd::service_limits`")
This should be merged before https://github.com/voxpupuli/puppet-systemd/pull/447.

Correctly interpolate variables in service_limits

---

manifests/timer_wrapper.pp
spec/defines/timer_wrapper_spec.rb

Don't treat unit names with `systemd::escape`. If you have `systemd::timer_wrapper` instances with names that contain special characters like slashes and umlauts this will result in a validation error.  In such cases you can produce the previous  behaviour by using `systemd::escape yourself` for example:
```puppet
systemd::timer_wrapper {systemd::escape( 'my_timer'):
ensure        => 'present',
command       => '/usr/bin/echo "Hello World"',
on_calendar   => '*:0/5',
}
```
It is possible that this change will create duplicate resources in case the resource name was escaped but the unescaped name is also valid. In those cases make sure to remove the duplicate, e.g. like so:
```puppet
systemd::timer_wrapper { systemd::escape("someTitle"):
ensure => absent,
}
```
Fixes #451

remove `systemd::escape` usage for `timer_wrapper`

---

REFERENCE.md
manifests/init.pp
manifests/resolved.pp
spec/classes/init_spec.rb

When `dns_stub_listener` and `dns_stub_listener_extra` are changed from a value to `undef` they don't get removed from the config.
There is plenty more settings  here that could use the same treatment I guess
Fixes #397

remove resolved settings from config when changed to `absent`

---

manifests/service_limits.pp

Fix typo in `systemd::service_limits` deprecation message

fix typo in service_limits deprecation message

---

REFERENCE.md
data/RedHat-family-9.yaml
manifests/init.pp
manifests/install.pp

This allows folks to set a specific name for systemd-oomd if it is a separate package from systemd (RHEL9 is this way).
The existing `install.pp` doesn't seem to have tests so...

Allow setting a specific package name for systemd-oomd

---

manifests/dropin_file.pp
spec/defines/dropin_file_spec.rb

Since multiple drop-in files of the same unit notify the same `Systemd::Daemon_reload` resource, changing a drop in file without `notify_service` still triggers a service refresh if at least one other drop-in file has `notify_service` set (default) regardless of it being changed.
Therefore, the `Systemd::Daemon_reload` should only be ordered before the `Service` but not notify it. The `service` will already be refreshed if the drop-in file changes and `notify_service` is set (default).
Consider the following Puppet code snippet with two drop-in files for the service `nginx.service`:
```Puppet
systemd::dropin_file {
default:
unit => 'nginx.service',
;
"restart.conf":
notify_service => false,
content        => @(EOT)
[Service]
Restart=on-failure
| EOT
,
;
"ulimit.conf":
content => @(EOT) …
```

fix: refresh service only based on drop-in file changes

---

data/RedHat-family-7.yaml
data/RedHat-family-8.yaml
data/RedHat-family-9.yaml
data/RedHat-family.yaml
spec/classes/init_spec.rb

CentOS Stream10 continues to have systemd-resolved in its own package.

Rework Red Hat resolved package list to be more future proof

---

README.md

`limits` should be `service_entry` as noted in
https://github.com/voxpupuli/puppet-systemd/pull/461/files#r1668626577.

README.md: correct service limits example

---

manifests/init.pp
metadata.json

For stdlib 9.x and later, the shell_escape function has been moved to stdlib::shell_escape.
This change breaks compatiblity with stdlib 8.x
Fixes #479

Replace deprecated `shell_escape` function with `stdlib::shell_escape`

---

REFERENCE.md
manifests/init.pp
manifests/udev/rule.pp
manifests/udevd.pp
spec/classes/init_spec.rb
spec/defines/udev_rules_spec.rb

Automatically reload udev rules after a change. 
To enable this feature use
```yaml
systemd::udev_reload: true
```
A rule with a `String` notification would be then appended with `Exec[systemd-udev_reload]`
```yaml
systemd::udev::rule:
notify: "Service[systemd-udevd]"
```
e.g. 
```
notify => [ Service[systemd-udevd], Exec[systemd-udev_reload] ]
```
would be used.
Fixes #484

Reload udev rules after change

---

README.md

`/etc/systemd/system` is the path used in the code: https://github.com/voxpupuli/puppet-systemd/blob/ff0c85e828b17ec485c834b89cd00fbc4fd90665/manifests/unit_file.pp#L73
Fixes #488.

README: fix path in example

---

REFERENCE.md
manifests/manage_dropin.pp
manifests/manage_unit.pp
spec/defines/manage_dropin_spec.rb
spec/defines/manage_unit_spec.rb
spec/type_aliases/systemd_unit_mount_spec.rb
templates/unit_file.epp
types/unit/mount.pp

Support addition `.mount` units in `systemd::manage_unit` and `systemd::manage_dropin`.
e.g.
```puppet
systemd::manage_unit { 'var-lib-sss-db.mount':
ensure      => $_use_ramdisk,
unit_entry  => {
'Description' => 'Mount a ram disk for sssd to use',
},
mount_entry => {
'What'    => 'tmpfs',
'Where'   => '/var/lib/sss/db',
'Type'    => 'tmpfs',
'Options' => "size=300M,mode=0700,uid=sssd,gid=sssd,rootcontext=system_u:object_r:sssd_var_lib_t:s0",
},
}
```
* https://www.freedesktop.org/software/systemd/man/latest/systemd.mount.html

Support Mount units for manage_unit or dropin types

---

REFERENCE.md
data/Debian-family.yaml
data/RedHat-family.yaml
manifests/init.pp
manifests/journal_remote.pp
manifests/journal_upload.pp
spec/classes/init_spec.rb
types/journalremotesettings.pp
types/journaluploadsettings.pp

add support for uploading journal to a remote server

add support for journal upload and remote server

---

data/RedHat-family-7.yaml
data/VirtuozzoLinux-7.yaml
metadata.json
spec/acceptance/nspwan_spec.rb
spec/defines/daemon_reload_spec.rb

* VirtuozzoLinux 7
* Fedora 38, 39
* Centos 7, 8
* RHEL 7

Drop EOL RHEL, CentOS, Fedora, VirtuozzoLinux versions

---

REFERENCE.md
manifests/manage_dropin.pp
manifests/manage_unit.pp
spec/defines/manage_dropin_spec.rb
spec/defines/manage_unit_spec.rb
spec/type_aliases/systemd_unit_swap_spec.rb
templates/unit_file.epp
types/unit/swap.pp

Let `.swap` unit files be managed with `systemd::manage_dropin` and `systemd::manage_unit`.
For example:
```puppet
systemd::manage_unit{'swapfile.swap':
ensure        => 'present',
active        => true,
enable        => true,
unit_entry    => {
'Description' => 'Enable a swapfile at /swapfile',
}
swap_entry    => {
'What' => '/swapfile',
}
install_entry => {
'WantedBy' => 'multi-user.target',
},
}
```
* https://www.freedesktop.org/software/systemd/man/latest/systemd.swap.html

Support management of Swap unit files

---

REFERENCE.md
manifests/manage_unit.pp

Without a correct UMask set the `mkswap` example fails due to permissions being too relaxed.

Correct UMask in mkswap example

---

CHANGELOG.md
README.md
metadata.json

Release 8.0.0

---

REFERENCE.md
manifests/manage_dropin.pp
manifests/manage_unit.pp
spec/defines/manage_dropin_spec.rb
spec/defines/manage_unit_spec.rb
spec/type_aliases/systemd_unit_link_spec.rb
spec/type_aliases/systemd_unit_match_spec.rb
spec/type_aliases/unit_spec.rb
templates/unit_file.epp
types/unit.pp
types/unit/link.pp
types/unit/match.pp

Addition of link unit support to `systemd::manage_unit` and `systemd::manage_dropin`.
* https://www.freedesktop.org/software/systemd/man/latest/systemd.link.html
This only adds a skeleton of the parameters that can be set.
More will be needed to be usable.

Add support for .link units and dropins

---

manifests/manage_dropin.pp

Correction content fail message "... swap_entry is only valid for swap units"
No One

Correction fail message "... swap_entry is only valid for swap units"

---

data/Ubuntu-24.04.yaml
spec/acceptance/resolved_spec.rb
spec/classes/init_spec.rb

Includes #524
`systemd-resolved` is in a separate package starting in Ubuntu 24.04, so we should define this in the hiera data (even though the `systemd` package recommends `systemd-resolved`, so normally the `systemd-resolved` package is installed anyway).

Define `systemd::resolved_package` for Ubuntu 24.04

---

spec/acceptance/resolved_spec.rb

Ubuntu 24.04 and newer have a separate `systemd-resolved` package.

`resolved` acceptance test: add Ubuntu 24.04

---

REFERENCE.md
data/Debian-family.yaml
manifests/init.pp
manifests/install.pp
spec/acceptance/resolved_spec.rb
spec/classes/init_spec.rb

Ensure Name Service Switch (NSS) libraries are installed when managing `systemd-resolved` on Debian family.
Fixes #526

Ensure NSS libraries are installed when managing `systemd-resolved` on Debian family

---

data/RedHat-family-10.yaml

With RHEL10 due out in May, here are the defaults for puppet-systemd.
The testsuite doesn't yet recognize EL10, so I'm leaving it out of the metadata until we can prove it out with the test suite.

Add defaults for RHEL10

---

REFERENCE.md
types/logindsettings.pp

Added the following settings:
* `DesignatedMaintenanceTime`
* `HandleHibernateKeyLongPress`
* `HandlePowerKeyLongPress`
* `HandleRebootKey`
* `HandleRebootKeyLongPress`
* `HandleSecureAttentionKey`
* `HandleSuspendKeyLongPress`
* `RebootKeyIgnoreInhibited`
* `RuntimeDirectoryInodesMax`
* `SleepOperation`
* `UserTasksMax`
Pulled from the list at https://www.freedesktop.org/software/systemd/man/latest/logind.conf.html

Add missing `Systemd::LogindSettings`

---

REFERENCE.md
manifests/networkd.pp
manifests/networkd/interface.pp
spec/classes/networkd_spec.rb
spec/data/rspec.yaml
spec/defines/networkd/interface_spec.rb

This PR contains 3 releated commits which probably should be reviewed separately:
- the first add spec tests to detect #560 issue.
- the scond commit fixes #560 by reworking the interaction inbetween systemd::networkd and systemd::networkd::interface which also:
- deprectates the type parameter in systemd::networkd::interface
since this is a duplicate information not needed.
- introduces the possibility to use one call of the
systemd::networkd::interface resource to generate link/netdev and
network file.
- the third one adds some additional spec tests for networkd
fixes: #560

networkd: fix broken implementation and add netdev and link file to spec tests
