voxpupuli/puppet-systemd

lib/facter/systemd.rb

This is a port of puppetlabs/facter#871

Add systemd facts

---

manifests/init.pp
spec/classes/init_spec.rb

Use the correct type on $service_limits

---

CHANGELOG.md
metadata.json

@raphink can we do a new release?

release 1.1.1

---

.sync.yml
CHANGELOG.md
Gemfile
Rakefile
metadata.json

We'll need to find a way to merge the CHANGELOG settings in the PDK template somehow…

Release 2.8.0

---

manifests/resolved.pp

this pull requests solved Issue 113

fix Issue 113

---

data/CentOS-8.yaml
data/OracleLinux-7.yaml
data/OracleLinux-8.yaml
data/RedHat-8.yaml
metadata.json

* Added EL8 support
* Added OracleLinux as a supported platform

Add EL8 Support

---

data/common.yaml
manifests/init.pp
manifests/journald.pp
spec/classes/init_spec.rb

This reverts commit b2ddb4c4fe87ec78c4ff8a44beb16a5ee052a0a0.

Revert "add option for persistent logging (#127)"

---

manifests/journald.pp

Comment was a copy-paste error from system.pp.

journald.pp: fix comment

---

manifests/dropin_file.pp
manifests/init.pp
manifests/journald.pp
manifests/logind.pp
manifests/network.pp
manifests/networkd.pp
manifests/resolved.pp
manifests/service_limits.pp
manifests/system.pp
manifests/timer.pp
manifests/timesyncd.pp
manifests/tmpfile.pp
manifests/tmpfiles.pp
manifests/unit_file.pp
types/journaldsettings.pp
types/journaldsettings/ensure.pp
types/logindsettings.pp
types/logindsettings/ensure.pp

puppet-lint flagged these items.

Resolve puppet-lint warnings

---

data/Ubuntu-20.04.yaml
metadata.json

add ubuntu2004

---

CHANGELOG.md
README.md
metadata.json

release 3.1.0

---

REFERENCE.md
manifests/dropin_file.pp
manifests/service_limits.pp
manifests/udev/rule.pp

Fix `Optional` datatype for non-optional parameters

---

manifests/network.pp
spec/defines/network_spec.rb

systemd::network: Validate if content/source are set for file resource

---

REFERENCE.md
manifests/network.pp

Add puppet-strings documentation for systemd::network

---

manifests/service_limits.pp
manifests/tmpfiles.pp

puppet-lint: fix top_scope_facts warnings

---

REFERENCE.md
manifests/init.pp
spec/classes/init_spec.rb

This is a rebase of https://github.com/voxpupuli/puppet-systemd/pull/212

Add additional hash parameters for defined types

---

data/Gentoo.yaml
metadata.json
spec/classes/init_spec.rb

Add Gentoo support

---

.msync.yml
Gemfile
lib/facter/systemd.rb
lib/puppet/provider/loginctl_user/ruby.rb
lib/puppet/type/loginctl_user.rb
spec/classes/init_spec.rb
spec/classes/tmpfiles_spec.rb
spec/defines/dropin_file_spec.rb
spec/defines/network_spec.rb
spec/defines/service_limits_spec.rb
spec/defines/timer_spec.rb
spec/defines/tmpfile_spec.rb
spec/defines/unit_file_spec.rb
spec/functions/escape_spec.rb
spec/spec_helper.rb
spec/unit/facter/systemd_spec.rb
spec/unit/facter/systemd_version_spec.rb
spec/unit/puppet/provider/loginctl_user/ruby_spec.rb
spec/unit/puppet/type/loginctl_user_spec.rb

modulesync 5.0.0

---

manifests/unit_file.pp
spec/defines/unit_file_spec.rb

Link the unit file to /dev/null when "enable => mask"

---

CHANGELOG.md
metadata.json

Release 3.5.2

---

REFERENCE.md
manifests/unit_file.pp
spec/defines/unit_file_spec.rb

unit_file: Implement hasrestart/hasstatus

---

CHANGELOG.md
metadata.json

Release 3.6.0

---

README.md
REFERENCE.md
manifests/unit_file.pp

document systemd::unit_file example with puppet-strings

---

CHANGELOG.md
REFERENCE.md
metadata.json

Release 3.8.0

---

CHANGELOG.md
REFERENCE.md
metadata.json

Release 3.9.0

---

README.md

Minor wordsmithing

---

REFERENCE.md
manifests/dropin_file.pp

The filename and unit parameter were documented incorrectly
as to which was the name variable.

Correct docs for name var of systemd::dropin_file

---

REFERENCE.md
data/Ubuntu-22.04.yaml
manifests/init.pp
metadata.json

Drop a few OS releases that are EOL and add some fresh Fedora ones.

Add support for Ubuntu 22.04

---

metadata.json

add support for {AlmaLinux,Rocky} {8,9}

---

CHANGELOG.md
metadata.json

Release 5.2.0

---

REFERENCE.md
types/unit/service.pp

add PrivateTmp and RuntimeDirectory

add PrivateTmp and RuntimeDirectory

---

REFERENCE.md
manifests/manage_unit.pp

fix socket service example syntax

---

metadata.json

Add OracleLinux 9 support

---

data/Debian-12.yaml
metadata.json

Add Debian 12 support

---

CHANGELOG.md
metadata.json

Release 6.1.0

---

REFERENCE.md
spec/type_aliases/systemd_unit_service_spec.rb
types/unit/service.pp

Adds support for the `UMask` directive in the `[Service]` section.

Add `UMask` to `Systemd::Unit::Service`

---

REFERENCE.md
types/unit/service.pp

Allow for the `StateDirectory` service option to be used.

Add `StateDirectory` to `Systemd::Unit::Service`

---

CHANGELOG.md
metadata.json

Release 6.4.0

---

REFERENCE.md
manifests/manage_unit.pp

Updates two sections of `REFERENCE.md` that contained invalid syntax, with the goal of making all examples in `REFERENCE.md` valid for paste-and-run execution.
Fixes #414

manage_unit: correct minor mistakes in examples

---

REFERENCE.md
manifests/manage_unit.pp
manifests/unit_file.pp
spec/defines/unit_file_spec.rb

Provide the possibility to disable service restart upon unit file change
Fixes #432

Make service restart upon unit file change optional

---

REFERENCE.md
types/unit/service.pp

Add NetworkNamespacePath as a valid key for unit service
Fixes #440

Add NetworkNamespacePath as a valid unit service configuration

---

spec/defines/service_limits_spec.rb

a51bc397953410ec03323fcbd6ef58d52ecf54a4 fixed a bug. Add a test to catch next time.

Add test case for interpolation bug in name of used types

---

REFERENCE.md
manifests/init.pp
manifests/timedatectl.pp
spec/classes/init_spec.rb

Add support for timedatectl to set timezone and hardware clock
Fixes: #377

Add support for timezone and hardware clock

---

REFERENCE.md
types/unit/service.pp

required for https://github.com/voxpupuli/puppet-prometheus/pull/735
https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#MemoryDenyWriteExecute=

add MemoryDenyWriteExecute to Systemd::Unit::Service type

---

manifests/timesyncd.pp

timesyncd.pp: Fix typo in documentation

---

README.md

Document changes done in #485.

Update readme to reflect changes in #485

---

REFERENCE.md
types/unit/service.pp

There are a few more options to systemd service units that are not present in the defined type.  This adds a handful of the missing options I noted.

Add a few more missing service options

---

README.md

I've bent over backwards to make this work, while the solution is much simpler than I thought it was.
Let's share the knowledge with the world so that others don't make the same mistake I did.
Closes: #510
Replaces: #511

docs: describe how to deploy systemd templates

---

REFERENCE.md
manifests/manage_dropin.pp
manifests/manage_unit.pp
spec/defines/manage_dropin_spec.rb
spec/defines/manage_unit_spec.rb
spec/type_aliases/systemd_unit_link_spec.rb
spec/type_aliases/systemd_unit_match_spec.rb
spec/type_aliases/unit_spec.rb
templates/unit_file.epp
types/unit.pp
types/unit/link.pp
types/unit/match.pp

Reverts voxpupuli/puppet-systemd#513
This makes no sense given the corrections to my understanding in #497

Revert "Add support for .link units and dropins"

---

REFERENCE.md
types/logindsettings.pp

Adds `UserStopDelaySec` to the list of valid `Systemd::LogindSettings`

Add `UserStopDelaySec` to `Systemd::LogindSettings`

---

spec/acceptance/user_service_spec.rb

`systemd::user_service` should be tested.

Add acceptance test for systemd::user_service

---

REFERENCE.md
manifests/timer_wrapper.pp
spec/defines/timer_wrapper_spec.rb

Add parameters so users can also set ExecStartPre and ExecStartPost options

timer_wrapper: Add pre/post commands

---

metadata.json
spec/acceptance/networkd_spec.rb

Add EL10 support
